name: scapy
version: git
summary: Packet manipulation program.
description: | A powerful Python-based interactive packet manipulation program and library.
 
grade: devmode
base: core18

architectures:  
  - build-on: amd64

parts:
  scapy:
    source: https://github.com/secdev/scapy.git
    source-tag: master
    plugin: python
    python-version: python3
    stage-packages:
      - ipython
      - pyx
      - cryptography>=2.0
      - matplotlib

apps:
  scapy:
    command: bin/scapy
